=== SAAF-Developers/saaf/test-home/conf/schema/permissions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"  targetNamespace="http://syssec.rub.de/SMAF" xmlns="http://syssec.rub.de/SMAF" elementFormDefault="qualified">
  <xs:element name="permissions">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="permission"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="permission">
    <xs:complexType>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
      <xs:attribute name="type" use="required" type="xs:string"/>
      <xs:attribute name="description" use="required" type="xs:string" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== SAAF-Developers/saaf/conf/permissions.xml
<?xml version="1.0" encoding="UTF-8"?>
<permissions xmlns="http://syssec.rub.de/SAAF"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://syssec.rub.de/SAAF schema/permissions.xsd">
	<permission name="android.permission.ACCESS_CHECKIN_PROPERTIES"
		type="platform" description="" />
	<permission name="android.permission.ACCESS_COARSE_LOCATION"
		type="platform" description="" />
	<permission name="android.permission.ACCESS_FINE_LOCATION"
		type="platform" description="" />
	<permission name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS"
		type="platform" description="" />
	<permission name="android.permission.ACCESS_MOCK_LOCATION"
		type="platform" description="" />
	<permission name="android.permission.ACCESS_NETWORK_STATE"
		type="platform" description="" />
	<permission name="android.permission.ACCESS_SURFACE_FLINGER"
		type="platform" description="" />
	<permission name="android.permission.ACCESS_WIFI_STATE"
		type="platform" description="" />
	<permission name="android.permission.ACCOUNT_MANAGER" type="platform"
		description="" />
	<permission name="android.permission.AUTHENTICATE_ACCOUNTS"
		type="platform" description="" />
	<permission name="android.permission.BATTERY_STATS" type="platform"
		description="" />
	<permission name="android.permission.BIND_ACCESSIBILITY_SERVICE"
		type="platform" description="" />
	<permission name="android.permission.BIND_APPWIDGET" type="platform"
		description="" />
	<permission name="android.permission.BIND_DEVICE_ADMIN"
		type="platform" description="" />
	<permission name="android.permission.BIND_INPUT_METHOD"
		type="platform" description="" />
	<permission name="android.permission.BIND_REMOTEVIEWS" type="platform"
		description="" />
	<permission name="android.permission.BIND_TEXT_SERVICE"
		type="platform" description="" />
	<permission name="android.permission.BIND_VPN_SERVICE" type="platform"
		description="" />
	<permission name="android.permission.BIND_WALLPAPER" type="platform"
		description="" />
	<permission name="android.permission.BLUETOOTH" type="platform"
		description="" />
	<permission name="android.permission.BLUETOOTH_ADMIN" type="platform"
		description="" />
	<permission name="android.permission.BRICK" type="platform"
		description="" />
	<permission name="android.permission.BROADCAST_PACKAGE_REMOVED"
		type="platform" description="" />
	<permission name="android.permission.BROADCAST_SMS" type="platform"
		description="" />
	<permission name="android.permission.BROADCAST_STICKY" type="platform"
		description="" />
	<permission name="android.permission.BROADCAST_WAP_PUSH"
		type="platform" description="" />
	<permission name="android.permission.CALL_PHONE" type="platform"
		description="" />
	<permission name="android.permission.CALL_PRIVILEGED" type="platform"
		description="" />
	<permission name="android.permission.CAMERA" type="platform"
		description="" />
	<permission name="android.permission.CHANGE_COMPONENT_ENABLED_STATE"
		type="platform" description="" />
	<permission name="android.permission.CHANGE_CONFIGURATION"
		type="platform" description="" />
	<permission name="android.permission.CHANGE_NETWORK_STATE"
		type="platform" description="" />
	<permission name="android.permission.CHANGE_WIFI_MULTICAST_STATE"
		type="platform" description="" />
	<permission name="android.permission.CHANGE_WIFI_STATE"
		type="platform" description="" />
	<permission name="android.permission.CLEAR_APP_CACHE" type="platform"
		description="" />
	<permission name="android.permission.CLEAR_APP_USER_DATA"
		type="platform" description="" />
	<permission name="android.permission.CONTROL_LOCATION_UPDATES"
		type="platform" description="" />
	<permission name="android.permission.DELETE_CACHE_FILES"
		type="platform" description="" />
	<permission name="android.permission.DELETE_PACKAGES" type="platform"
		description="" />
	<permission name="android.permission.DEVICE_POWER" type="platform"
		description="" />
	<permission name="android.permission.DIAGNOSTIC" type="platform"
		description="" />
	<permission name="android.permission.DISABLE_KEYGUARD" type="platform"
		description="" />
	<permission name="android.permission.DUMP" type="platform"
		description="" />
	<permission name="android.permission.EXPAND_STATUS_BAR"
		type="platform" description="" />
	<permission name="android.permission.FACTORY_TEST" type="platform"
		description="" />
	<permission name="android.permission.FLASHLIGHT" type="platform"
		description="" />
	<permission name="android.permission.FORCE_BACK" type="platform"
		description="" />
	<permission name="android.permission.GET_ACCOUNTS" type="platform"
		description="" />
	<permission name="android.permission.GET_PACKAGE_SIZE" type="platform"
		description="" />
	<permission name="android.permission.GET_TASKS" type="platform"
		description="" />
	<permission name="android.permission.GLOBAL_SEARCH" type="platform"
		description="" />
	<permission name="android.permission.HARDWARE_TEST" type="platform"
		description="" />
	<permission name="android.permission.INJECT_EVENTS" type="platform"
		description="" />
	<permission name="android.permission.INSTALL_LOCATION_PROVIDER"
		type="platform" description="" />
	<permission name="android.permission.INSTALL_PACKAGES" type="platform"
		description="" />
	<permission name="android.permission.INTERNAL_SYSTEM_WINDOW"
		type="platform" description="" />
	<permission name="android.permission.INTERNET" type="platform"
		description="" />
	<permission name="android.permission.KILL_BACKGROUND_PROCESSES"
		type="platform" description="" />
	<permission name="android.permission.MANAGE_ACCOUNTS" type="platform"
		description="" />
	<permission name="android.permission.MANAGE_APP_TOKENS"
		type="platform" description="" />
	<permission name="android.permission.MASTER_CLEAR" type="platform"
		description="" />
	<permission name="android.permission.MODIFY_AUDIO_SETTINGS"
		type="platform" description="" />
	<permission name="android.permission.MODIFY_PHONE_STATE"
		type="platform" description="" />
	<permission name="android.permission.MOUNT_FORMAT_FILESYSTEMS"
		type="platform" description="" />
	<permission name="android.permission.MOUNT_UNMOUNT_FILESYSTEMS"
		type="platform" description="" />
	<permission name="android.permission.NFC" type="platform"
		description="" />
	<permission name="android.permission.PERSISTENT_ACTIVITY"
		type="platform" description="" />
	<permission name="android.permission.PROCESS_OUTGOING_CALLS"
		type="platform" description="" />
	<permission name="android.permission.READ_CALENDAR" type="platform"
		description="" />
	<permission name="android.permission.READ_CALL_LOG" type="platform"
		description="" />
	<permission name="android.permission.READ_CONTACTS" type="platform"
		description="" />
	<permission name="android.permission.READ_EXTERNAL_STORAGE"
		type="platform" description="" />
	<permission name="android.permission.READ_FRAME_BUFFER"
		type="platform" description="" />
	<permission name="android.permission.READ_INPUT_STATE" type="platform"
		description="" />
	<permission name="android.permission.READ_LOGS" type="platform"
		description="" />
	<permission name="android.permission.READ_PHONE_STATE" type="platform"
		description="" />
	<permission name="android.permission.READ_PROFILE" type="platform"
		description="" />
	<permission name="android.permission.READ_SMS" type="platform"
		description="" />
	<permission name="android.permission.READ_SOCIAL_STREAM"
		type="platform" description="" />
	<permission name="android.permission.READ_SYNC_SETTINGS"
		type="platform" description="" />
	<permission name="android.permission.READ_SYNC_STATS" type="platform"
		description="" />
	<permission name="android.permission.READ_USER_DICTIONARY"
		type="platform" description="" />
	<permission name="android.permission.REBOOT" type="platform"
		description="" />
	<permission name="android.permission.RECEIVE_BOOT_COMPLETED"
		type="platform" description="" />
	<permission name="android.permission.RECEIVE_MMS" type="platform"
		description="" />
	<permission name="android.permission.RECEIVE_SMS" type="platform"
		description="" />
	<permission name="android.permission.RECEIVE_WAP_PUSH" type="platform"
		description="" />
	<permission name="android.permission.RECORD_AUDIO" type="platform"
		description="" />
	<permission name="android.permission.REORDER_TASKS" type="platform"
		description="" />
	<permission name="android.permission.RESTART_PACKAGES" type="platform"
		description="" />
	<permission name="android.permission.SEND_SMS" type="platform"
		description="" />
	<permission name="android.permission.SET_ACTIVITY_WATCHER"
		type="platform" description="" />
	<permission name="android.permission.SET_ALWAYS_FINISH"
		type="platform" description="" />
	<permission name="android.permission.SET_ANIMATION_SCALE"
		type="platform" description="" />
	<permission name="android.permission.SET_DEBUG_APP" type="platform"
		description="" />
	<permission name="android.permission.SET_ORIENTATION" type="platform"
		description="" />
	<permission name="android.permission.SET_POINTER_SPEED"
		type="platform" description="" />
	<permission name="android.permission.SET_PREFERRED_APPLICATIONS"
		type="platform" description="" />
	<permission name="android.permission.SET_PROCESS_LIMIT"
		type="platform" description="" />
	<permission name="android.permission.SET_TIME" type="platform"
		description="" />
	<permission name="android.permission.SET_TIME_ZONE" type="platform"
		description="" />
	<permission name="android.permission.SET_WALLPAPER" type="platform"
		description="" />
	<permission name="android.permission.SET_WALLPAPER_HINTS"
		type="platform" description="" />
	<permission name="android.permission.SIGNAL_PERSISTENT_PROCESSES"
		type="platform" description="" />
	<permission name="android.permission.STATUS_BAR" type="platform"
		description="" />
	<permission name="android.permission.SUBSCRIBED_FEEDS_READ"
		type="platform" description="" />
